### ISSUE TITLE
FDroid iteration 8 build failing

### ISSUE THREAD

**Issue by flide** [8VIM/8VIM#236]
****
Build failing on fdroid for iteration 8 stating gradle needs java 11 but only java 8 is available

**To Reproduce**
1. See attached build log for error

**Expected behavior**
Iteration 8 should have been released on fdroid

**Build Log**

Traceback (most recent call last): File "/home/fbuild/fdroidserver/fdroidserver/build.py", line 1127, in main options.onserver, options.refresh): File "/home/fbuild/fdroidserver/fdroidserver/build.py", line 885, in trybuild build_server(app, build, vcs, build_dir, output_dir, log_dir, force) File "/home/fbuild/fdroidserver/fdroidserver/build.py", line 268, in build_server str(output, 'utf-8')) fdroidserver.exception.BuildException: Build.py failed on server for inc.flide.vi8:iteration-8 ==== detail begin ==== == Installed Android Tools == 2022-01-03 13:53:22,787 DEBUG: Reading 'config.yml' 2022-01-03 13:53:22,796 INFO: Using /opt/android-sdk/build-tools/29.0.3/apksigner 2022-01-03 13:53:22,799 INFO: Creating log directory 2022-01-03 13:53:22,799 INFO: Creating temporary directory 2022-01-03 13:53:22,799 INFO: Creating output directory 2022-01-03 13:53:22,801 DEBUG: Getting git vcs interface for https://github.com/flide/8VIM 2022-01-03 13:53:22,802 DEBUG: > git --version git version 2.11.0 2022-01-03 13:53:23,022 INFO: Using git version 2.11.0 2022-01-03 13:53:23,022 DEBUG: Checking iteration-8 2022-01-03 13:53:23,022 INFO: Building version iteration-8 (8) of inc.flide.vi8 2022-01-03 13:53:23,023 DEBUG: > sudo passwd --lock root passwd: password expiry information changed. 2022-01-03 13:53:23,231 DEBUG: > sudo SUDO_FORCE_REMOVE=yes dpkg --purge sudo (Reading database ... 64893 files and directories currently installed.) Removing sudo (1.8.19p1-2.1+deb9u3) ... Purging configuration files for sudo (1.8.19p1-2.1+deb9u3) ... Processing triggers for systemd (232-25+deb9u13) ... 2022-01-03 13:53:28,818 INFO: Getting source for revision 94d1973644a051aac170f3178d33160094eea607 2022-01-03 13:53:28,830 DEBUG: Directory: build/inc.flide.vi8 2022-01-03 13:53:28,830 DEBUG: > git rev-parse --show-toplevel 2022-01-03 13:53:29,035 DEBUG: Directory: build/inc.flide.vi8 2022-01-03 13:53:29,035 DEBUG: > git submodule foreach --recursive git reset --hard 2022-01-03 13:53:29,140 DEBUG: Directory: build/inc.flide.vi8 2022-01-03 13:53:29,140 DEBUG: > git reset --hard 2022-01-03 13:53:29,486 DEBUG: Directory: build/inc.flide.vi8 2022-01-03 13:53:29,487 DEBUG: > git submodule foreach --recursive git clean -dffx 2022-01-03 13:53:29,592 DEBUG: Directory: build/inc.flide.vi8 2022-01-03 13:53:29,592 DEBUG: > git clean -dffx 2022-01-03 13:53:29,706 DEBUG: Directory: build/inc.flide.vi8 2022-01-03 13:53:29,706 DEBUG: > git -c core.askpass=/bin/true -c core.sshCommand=/bin/false -c url.https://.insteadOf=ssh:// -c url.https://u:p@bitbucket.org/.insteadOf=git@bitbucket.org: -c url.https://u:p@bitbucket.org.insteadOf=git://bitbucket.org -c url.https://u:p@bitbucket.org.insteadOf=https://bitbucket.org -c url.https://u:p@github.com/.insteadOf=git@github.com: -c url.https://u:p@github.com.insteadOf=git://github.com -c url.https://u:p@github.com.insteadOf=https://github.com -c url.https://u:p@gitlab.com/.insteadOf=git@gitlab.com: -c url.https://u:p@gitlab.com.insteadOf=git://gitlab.com -c url.https://u:p@gitlab.com.insteadOf=https://gitlab.com fetch origin 2022-01-03 13:53:30,016 DEBUG: Directory: build/inc.flide.vi8 2022-01-03 13:53:30,017 DEBUG: > git -c core.askpass=/bin/true -c core.sshCommand=/bin/false -c url.https://.insteadOf=ssh:// -c url.https://u:p@bitbucket.org/.insteadOf=git@bitbucket.org: -c url.https://u:p@bitbucket.org.insteadOf=git://bitbucket.org -c url.https://u:p@bitbucket.org.insteadOf=https://bitbucket.org -c url.https://u:p@github.com/.insteadOf=git@github.com: -c url.https://u:p@github.com.insteadOf=git://github.com -c url.https://u:p@github.com.insteadOf=https://github.com -c url.https://u:p@gitlab.com/.insteadOf=git@gitlab.com: -c url.https://u:p@gitlab.com.insteadOf=git://gitlab.com -c url.https://u:p@gitlab.com.insteadOf=https://gitlab.com remote prune origin 2022-01-03 13:53:30,338 DEBUG: Directory: build/inc.flide.vi8 2022-01-03 13:53:30,339 DEBUG: > git -c core.askpass=/bin/true -c core.sshCommand=/bin/false -c url.https://.insteadOf=ssh:// -c url.https://u:p@bitbucket.org/.insteadOf=git@bitbucket.org: -c url.https://u:p@bitbucket.org.insteadOf=git://bitbucket.org -c url.https://u:p@bitbucket.org.insteadOf=https://bitbucket.org -c url.https://u:p@github.com/.insteadOf=git@github.com: -c url.https://u:p@github.com.insteadOf=git://github.com -c url.https://u:p@github.com.insteadOf=https://github.com -c url.https://u:p@gitlab.com/.insteadOf=git@gitlab.com: -c url.https://u:p@gitlab.com.insteadOf=git://gitlab.com -c url.https://u:p@gitlab.com.insteadOf=https://gitlab.com fetch --prune --tags --force origin 2022-01-03 13:53:30,644 DEBUG: Directory: build/inc.flide.vi8 2022-01-03 13:53:30,645 DEBUG: > git remote set-head origin --auto 2022-01-03 13:53:31,059 DEBUG: Directory: build/inc.flide.vi8 2022-01-03 13:53:31,059 DEBUG: > git checkout -f 94d1973644a051aac170f3178d33160094eea607 2022-01-03 13:53:31,267 DEBUG: Directory: build/inc.flide.vi8 2022-01-03 13:53:31,267 DEBUG: > git clean -dffx 2022-01-03 13:53:31,378 INFO: Creating local.properties file at build/inc.flide.vi8/local.properties 2022-01-03 13:53:31,378 INFO: Creating local.properties file at build/inc.flide.vi8/8vim/local.properties 2022-01-03 13:53:31,379 DEBUG: Removing debuggable flags from build/inc.flide.vi8/8vim 2022-01-03 13:53:31,387 INFO: Cleaning Gradle project... 2022-01-03 13:53:31,388 DEBUG: Directory: build/inc.flide.vi8/8vim 2022-01-03 13:53:31,388 DEBUG: > /home/vagrant/fdroidserver/gradlew-fdroid clean Found 7.0.2 via distributionUrl Running /opt/gradle/versions/7.0.2/bin/gradle clean Welcome to Gradle 7.0.2! Here are the highlights of this release: - File system watching enabled by default - Support for running with and building Java 16 projects - Native support for Apple Silicon processors - Dependency catalog feature preview For more details see https://docs.gradle.org/7.0.2/release-notes.html To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.0.2/userguide/gradle_daemon.html#sec:disabling_the_daemon. Daemon will be stopped at the end of the build FAILURE: Build failed with an exception. * Where: Build file '/home/vagrant/build/inc.flide.vi8/8vim/build.gradle' line: 1 * What went wrong: A problem occurred evaluating project ':8vim'. > Failed to apply plugin 'com.android.internal.application'. > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8. You can try some of the following options: - changing the IDE settings. - changing the JAVA_HOME environment variable. - changing `org.gradle.java.home` in `gradle.properties`. * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 20s 2022-01-03 13:53:52,499 ERROR: Could not build app inc.flide.vi8: Error cleaning inc.flide.vi8:iteration-8 ==== detail begin ==== Found 7.0.2 via distributionUrl Running /opt/gradle/versions/7.0.2/bin/gradle clean Welcome to Gradle 7.0.2! Here are the highlights of this release: - File system watching enabled by default - Support for running with and building Java 16 projects - Native support for Apple Silicon processors - Dependency catalog feature preview For more details see https://docs.gradle.org/7.0.2/release-notes.html To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.0.2/userguide/gradle_daemon.html#sec:disabling_the_daemon. Daemon will be stopped at the end of the build FAILURE: Build failed with an exception. * Where: Build file '/home/vagrant/build/inc.flide.vi8/8vim/build.gradle' line: 1 * What went wrong: A problem occurred evaluating project ':8vim'. > Failed to apply plugin 'com.android.internal.application'. > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8. You can try some of the following options: - changing the IDE settings. - changing the JAVA_HOME environment variable. - changing `org.gradle.java.home` in `gradle.properties`. * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 20s ==== detail end ==== 2022-01-03 13:53:52,500 DEBUG: Error encoutered, stopping by user request. ==== detail end ====

**Comment by flide** [comment]
Seems like the build was successful after all, iteration 8 is available on f-droid.
